### ISSUE TITLE
Support parallel deployments and SDL group deployments

### ISSUE THREAD

**Issue by joao-luna-98** [joao-luna-98/terraform-provider-akash#8]
This provider needs to be performant and allow deployments to happen in parallel. Several resources can be created without specifying all of them in a single SDL. This allows for fine grained control over the resources through the Terraform state.

*This issue will be updated with more detailed information as this gets investigated.*

## Limitations
Due to the way the Akash Network works, the DSEQ value is changed every block which is ~6 seconds at the time of this writing, thus for every deployment creation in that time frame the DSEQ is the same.

## Features
The provider must:
- [ ] Handle deployments on the same block from the same account
- [ ] Handle deployment groups on the same/different providers (check Multiple Providers Deployment)
- [ ] Provide filtering of providers in a per GSEQ fashion.

### Multiple Providers Deployment
A deployment could be deployed to multiple providers in this type of example SDL:

```yaml
---
version: "2.0"

services:
  supermario:
    image: pengbai/docker-supermario 
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    supermario:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    akash:
      pricing:
        supermario: 
          denom: uakt
          amount: 10000
    akash2:
      pricing:
        supermario: 
          denom: uakt
          amount: 10000
    akash3:
      pricing:
        supermario: 
          denom: uakt
          amount: 10000

deployment:
  supermario:
    akash:
      profile: supermario
      count: 1
    akash2:
      profile: supermario
      count: 1
    akash3:
      profile: supermario
      count: 1
```
